# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and Test Package

on:
  push:
    branches: [ "main", "skymoore/devops" ]
  pull_request:
    branches: [ "main", "skymoore/devops" ]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        python -m poetry install

    - name: Build and Install package
      run: |
        python -m poetry build
        python -m poetry install
        
    - name: Test
      run: |
        python -m poetry run python tests/tests.py 